Repository rebel1324/NutScript, pull requests merged in 2019-02, with the labels that each got.

#293 Music Volume Config
  plugins/multichar/plugins/charselect/derma/cl_bg_music.lua
  plugins/multichar/plugins/charselect/sh_plugin.lua
Labels: Beta Branch, Enhancement, Waiting for Merge

#294 Create _quantity column for 1.1 compatibility
  gamemode/core/hooks/sv_hooks.lua
Labels: Beta Branch, Bug, Fix, Waiting for Review

#296 Fixed equip in storage after restarts
  plugins/storage/sv_storage.lua
Labels: Fix, Waiting for Review

#297 Fallback to char-skin instead 0 on unwear outfit
  gamemode/items/base/sh_outfit.lua
Labels: Enhancement, Waiting for Review

#295 No PostInitialize in nut_storage
  plugins/storage/entities/entities/nut_storage/init.lua
Labels: Fix, Waiting for Merge
